

PACKET_SIZE = 400

TYPE_CONTROL	= 1
TYPE_DATA		= 2

SUBTYPE_REGISTER 	= 1
SUBTYPE_ALIVE	 	= 2
SUBTYPE_ACK		 	= 3

SUBTYPE_HOST_READY	= 11
SUBTYPE_REQ_HOST 	= 12
SUBTYPE_AGENT_ADDR	= 13
SUBTYPE_NACK		= 14

SUBTYPE_PROBING		= 15
SUBTYPE_SUCCESS		= 16

SPECTYPE_CLIENTNAME 	= 1
SPECTYPE_HOSTNAME 		= 2
SPECTYPE_SERVICENAME 	= 3
SEPCTYPE_ACK_SEQ_NR		= 4

LEN_CLIENTNAME 	= 64
LEN_HOSTNAME 	= 64
LEN_SERVICENAME = 64
